name: Revisar y publicar

on:
  push:
    paths:
      - 'programas/**.c'

jobs:
  revisar:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Instalar Python
        run: sudo apt-get install python3

      - name: Dar permisos
        run: chmod +x scripts/revisar.sh

      - name: Ejecutar revisión
        run: ./scripts/revisar.sh

           - name: Generar página web
        run: python3 scripts/generar_html.py

        - name: Verificar contenido de la carpeta web
  run: ls -l web/

- name: Mostrar contenido de index.html
  run: cat web/index.html


      - name: Configurar Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Publicar en GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./web
